cloud:
  aws:
    credentials:
      access-key: AKIAXXTFF2PMREK7FGTT
      secret-key: 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
    region:
      static: ap-southeast-1
    stack:
      auto: false
  dinary:
    name: dfnaeu8gs
    api_key: 994425532289159
    api_secret: TUmEMKIRdPqjlkA6WoO1WyTnzcA
    api_environment: CLOUDINARY_URL=cloudinary://368494898434464:LHqjt4jt3uYq0k3hqNYASb38o1I@dfnaeu8gs

application:
  bucket:
    name: encare
  security:
    secret-key: iamsixblack

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 8080